### ISSUE TITLE
Создать компонент сервис для работы с сервисом деплоя

### ISSUE THREAD

**Issue by r331** [faasj/gateway#21]
Для запуска функции ее нужно загрузить в кубер. За работу с кубером у нас будет отвечать сервис deployer, который будет создавать поды в кубере через kube api.
На стороне гейтвея нужно создать DTO которое мы будем передавать в сервис деплоя.
class DeployDto{
    private String serviceName;
    private String version;
    private String image;
    private String envProcess;
    private Map<String, String> envVars;
    private Map<String, String> labels;
    private Map<String, String> annotations;
    private Map<String, String> limits;
    private Map<String, String> requests;
}
В сервсе должны быть следующие методы:
deployFunction(UUID functionId)
Optional<DeployDto> findInstance(UUID serviceName)

**Comment by i7bro** [comment]
В optional мы DeployDto возвращаем?
