### ISSUE TITLE
Спроектировать сущности для хранения функции в базе данных Postgresql

### ISSUE THREAD

**Issue by r331** [faasj/gateway#3]
Добавить зависимость в проект, а так же написать сущности, которые в нем будут храниться.
https://mkyong.com/spring-boot/spring-boot-spring-data-jpa-postgresql/

Нам нужно подумать о том, какие поля мы должны хранить в базе данных.
И разработать скрипты для создания таблиц.

https://spring.io/guides/gs/accessing-data-jpa/

**Comment by i7bro** [comment]
Думаю в FunctionEntity можно хранить всё, что есть в dto, +functionId, create_date: 

UUID functionId;
String name;
String code;
String description;
String image;
String runtime;
LocalDateTime createDate;
UUID projectId;
Map<String, String> tags;
Map<String, String> environmentVariables;
Map<String, String> limits;
Map<String, String> requests;

**Comment by r331** [comment]
А поле runtime для чего добавляется?

**Comment by i7bro** [comment]
Если только Java будет, то не нужно 😅

**Comment by r331** [comment]
Добавим еще LocalDateTime updateDate.
Вместо рантайма можем добавить сслыку на enum возможных теймплитов.
а так же стоит подумать где хранить состояние функции

**Comment by i7bro** [comment]
Состояние, в смысле, поля функции или отдельное поле, её активность-неактивность?

**Comment by r331** [comment]
Имел ввиду активность, готова не готова, но пожалуй не будем сейчас этого.
