### ISSUE TITLE
Спроектировать сущности для хранения проектов в базе данных Postgresql 

### ISSUE THREAD

**Issue by r331** [faasj/gateway#4]
Добавить зависимость в проект, а так же написать сущности, которые в нем будут храниться.
https://mkyong.com/spring-boot/spring-boot-spring-data-jpa-postgresql/

Нам нужно подумать о том, какие поля мы должны хранить в базе данных.
И разработать скрипты для создания таблиц.

https://spring.io/guides/gs/accessing-data-jpa/

**Comment by i7bro** [comment]
Ориентируемся на ДТО, добавляем porjectId, createDate, updateDate. 

Не совсем понятно, что будет хранится в tags.

**Comment by r331** [comment]
Теги для функции. Например можно навесить теги lang: java или lang:nodejs. Потом пользователь может по ним проводить поиск.

**Comment by i7bro** [comment]
а теги в проекте тоже нужны для поиска проекта по тегам?

**Comment by r331** [comment]
Да, чтобы администратор мог искать по всем проектам пользователей
